[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

; Aqui você declara as dependências. O PlatformIO baixa sozinho!
lib_deps =
    painlessmesh/painlessMesh @ ^1.5.0
    bblanchon/ArduinoJson @ ^7.0.4
    crankyoldgit/IRremoteESP8266 @ ^2.8.6