; === Configurações Globais (Aplicadas a todos) ===
[env]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

; Aqui você declara as dependências. O PlatformIO baixa sozinho!
lib_deps =
    painlessmesh/painlessMesh @ ^1.5.0
    bblanchon/ArduinoJson @ ^7.0.4
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    
; === Ambiente da PONTE (A ESP conectada ao PC via Qt) ===
[env:esp_ponte]
build_src_filter = +<bridge.cpp> -<node.cpp>

; === Ambiente dos NÓS (As ESPs que ficam nos ares-condicionados) ===
[env:esp_no]
build_src_filter = +<node.cpp> -<bridge.cpp>